"""Shared Tkinter UI constants."""

APP_TITLE = "GN Estruturas - Calculadoras"

HOME_WIDTH = 360
HOME_HEIGHT = 320

PLACEHOLDER_WIDTH = 420
PLACEHOLDER_HEIGHT = 220
LIFTING_WIDTH = 760
LIFTING_HEIGHT = 680
ANCHORAGE_WIDTH = 760
ANCHORAGE_HEIGHT = 680
REBAR_CONVERTER_WIDTH = 280
REBAR_CONVERTER_HEIGHT = 320

WINDOW_PAD = 14
GROUP_PAD = 10
GAP = 8
FIELD_GAP = 4
ROW_PAD = 2
STATUS_PAD_X = 6
STATUS_PAD_Y = 5

BUTTON_WIDTH = 28

BG_COLOR = "#f5f5f5"
PANEL_COLOR = "#fbfbfb"
SURFACE_COLOR = "#ffffff"
TEXT_COLOR = "#111111"
MUTED_TEXT_COLOR = "#444444"
RESULT_BG_COLOR = "#efefef"
BORDER_COLOR = "#d6d6d6"
LINK_COLOR = "#1d4ed8"
WARNING_TEXT_COLOR = "#7c2d12"
ERROR_TEXT_COLOR = "#c62828"

OK_BG_COLOR = "#e8f5e9"
OK_TEXT_COLOR = "#0b6b2b"
OK_BORDER_COLOR = "#b7dfc0"

FAIL_BG_COLOR = "#fdecec"
FAIL_TEXT_COLOR = "#9b1c1c"
FAIL_BORDER_COLOR = "#f0b8b8"

INVALID_BG_COLOR = "#fff7ed"
INVALID_TEXT_COLOR = "#9a3412"
INVALID_BORDER_COLOR = "#fed7aa"

DEFAULT_ENTRY_STYLE = "TEntry"
INVALID_ENTRY_STYLE = "Invalid.TEntry"

SKETCH_CONCRETE_FILL = "#e2e8f0"
SKETCH_CONCRETE_BORDER = "#7c8794"
SKETCH_LABEL_COLOR = "#334155"
SKETCH_MUTED_COLOR = "#475569"
SKETCH_DIMENSION_COLOR = "#1d4ed8"
SKETCH_HATCH_COLOR = "#cbd5e1"
SKETCH_WELD_COLOR = "#0f172a"
SKETCH_CANVAS_BORDER = "#d8d8d8"
